### ISSUE TITLE
Folder Name.

### ISSUE THREAD

**Issue by ycpatel813** [marcoliceti/angular-uploads#5]
Hi,
 This is an awesome directive. I have one question, Is there a possible to get folder name?.

Thank you.

**Comment by marcoliceti** [comment]
Hi, thanks :)

> Is there a possible to get folder name?

It should be, but right now it's **not** supported.

This is the [FileSystemEntry](https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry). As you can see, there _is_ a `name` property.

This means that while recursively exploring a folder **I can** collect the names of any subfolder.

But this is not exactly the goal of the directive. The main purpose is to just select a bunch of files. Maybe I can add an option that changes the input for the callback. Instead of an array of files, I could invoke the callback with an array of objects with the following properties:

| Name | Description |
| --- | --- |
| is_file | Boolean indicating whether this object represents a regular file. If not, it is a directory. |
| file | A reference to the actual file. Will be `undefined` if `is_file` is falsy. |
| name | Name of the file or directory. |

However, this requires a little bit of work and should be tested too. So... I'll try to add this feature in future, but I can't say when it will be ready :-/

**Comment by ycpatel813** [comment]
If it will take too much time please don't do. 
Thanks :)  for an update.
